maps = {}
startingMap = "Temple Center"

maps["Temple Center"] = {map:
	   ["XXXXXXXXXXXXXXXXXXXXXX~~~XXXXXXXXXXXXXXXXXXXX",
		"                      ```                    ",
		"                      ```                    ",
		"                      ```                    ",
		"                      ```                    ",
		"X                     ```       X      XXXXXX",
		"X                     ```                   X",
		"X           XXX       ```                   X",
		"X                   X ``` XXX               X",
		"X     X               ```                   X",
		"X                     ```                   X",
		"X                     ```                   X",
		"XX                    ```                   X",
		"X                     ```                   X",
		"X        X            ```                   X",
		"X   XXX               ```                   X",
		"X                     ```                   X",
		"            X         ```           X        ",
		"            X       X ```  X        X        ",
		"            XX~~~~~~X~~~~~~X~~~~~~~~X        ",
		"           XXX~~XX~~X~~XX~~X~~~XX~~~XX       ",
		"XXXXXXXXXXXXXXXXXXXXX~~XXXXXXXXXXXXXXXXXXXXXX"],
		nExit: "Windswept Well",
		neExit: "Bell Tower",
		seExit: "Old Shrine",
		sExit: "Caldera Lake",
		swExit: "Underhalls",
		nwExit: "Reflecting Pool"}

maps["Old Shrine"] = {map:
   	   ["XXXXXXXX      XXXXXX      XXXXXX      XXXXXXX",
		"X                                           X",
		"X                                           X",
		"X                                           X",
		"X                                           X",
		"X                                    XXXXXXXX",
		"                                     #       ",
		"                                     #       ",
		"                                     #       ",
		"                                     #       ",
		"XX                     $             #     XX",
		"X       XXXXXX                  XXXXXX      X",
		"X                   XXXXXX                  X",
		"                                            X",
		"      X                                     X",
		"                X            X              X",
		"                                            X",
		"XXX                                         X",
		"*********************************************",
		"*********************************************",
		"*********************************************",
		"*********************************************"],
		nExit: "Bell Tower",
		neExit: "Garden Courtyard",
		seExit: null,
		sExit: null,
		swExit: "Caldera Lake",
		nwExit: "Temple Center",
		item: {enabled: true,
			skill: "fireDash",
			desc: "You can now dash! Press Z while on the ground to rocket forward a short distance, ignoring gravity!"}}

maps["Bell Tower"] = {map:
	   ["XXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXX",
		"      #                                     X",
		"      #                                     X",
		"      #                                     X",
		"      #                                     X",
		"X##XXXXXXX      $                           X",
		"X                                           X",
		"X             XXXXXX      XXXXXXXXXXXXXXXXXXX",
		"X                               X           X",
		"X                               X           X",
		"X                     XX        X           X",
		"X                               X           X",
		"                                X            ",
		"      XX      XXXXXX      XXXXXXX            ",
		"                                      X      ",
		"                                      X      ",
		"XXX                                   XXXXXXX",
		"X                                           X",
		"X                                           X",
		"X    X                                      X",
		"X    X                                      X",
		"XXXXXXXX      XXXXXX      XXXXXX      XXXXXXX"],
		nExit: "Horizon Canopy",
		neExit: null,
		seExit: "Garden Courtyard",
		sExit: "Old Shrine",
		swExit: "Temple Center",
		nwExit: "Windswept Well",
		item: {enabled: true,
			skill: "airJump",
			desc:"You can now double jump! Press the jump key while falling to jump again in mid-air! You can only double jump once before landing."}}

maps["Reflecting Pool"] = {map:
	   ["XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   X",
		"X                                           X",
		"X                                           X",
		"X                                           X",
		"X                                           X",
		"X $                                         X",
		"X                                          `~",
		"XXXXXXXX          XX      XX              `~~",
		"X                                        `~~~",
		"X                                       `~~~~",
		"X                              XX       `XXXX",
		"X                                       `   X",
		"                                        `    ",
		"                                    XX  `    ",
		"                                        `    ",
		"                                        `    ",
		"X                                       `XXXX",
		"X                                  `~~~~~~~~X",
		"X                            `~~~~~~X~~~~~~~X",		
		"X                      `~~~~~~X~~~~~X~~~~~~~X",
		"X     `~~~~~~~~~~~~~~~~~X~~~~~X~~~~~X~~~~~~~X",
		"X     `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"],
		nExit: "Cloud Castle",
		neExit: "Windswept Well",
		seExit: "Temple Center",
		sExit: "Underhalls",
		swExit: "Six Towers",
		nwExit: null,
		item: {enabled: true,
			skill: "waterSurf",
			desc: "You can now surf! You won't sink in water while moving at top speed! If you stop, slow down, or turn around, you'll start sinking."}}

maps["Underhalls"] = {map:
	   ["X     `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
		"X     `                                     X",
		"XXX   `                                     X",
		"X     `                                     X",
		"X     `                                     X",
		"XXXXX `                                     X",
		"      `                                      ",
		"      `                                      ",
		"      ` XXXXX                                ",
		"      `                                      ",
		"XX    `                                  XXXX",
		"X   $ `                                     X",
		"X     `                                     X",
		"X###X `                                     X",
		"X#### `                              X      X",
		"X#### `   XXXX                       XX     X",
		"XXXXX `                                     X",
		"X~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~X~~~~~~~~~~~",
		"X~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~XX~~~~~~~~~~~",
		"X~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~XXX~~~~~~~~~~~",
		"X~~~~~~~~~~~~~~~~~~~~~~~~~~~~~XXXX~~~~~~~~~~~",
		"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"],
		nExit: "Reflecting Pool",
		neExit: "Temple Center",
		seExit: "Caldera Lake",
		sExit: null,
		swExit: null,
		nwExit: "Six Towers",
		item: {enabled: true,
			skill: "earthSmash",
			desc: "You can now ground pound! Crouch and press Z to smash green blocks beneath you!"}}

maps["Six Towers"] = {map:
	   ["XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
		"X                                  X         ",
		"X                                  X         ",
		"X                                  X         ",
		"X                                  X         ",
		"X                                  X        X",
		"X                                  X        X",
		"X   X    X       XXXXXXXXXXXXX     X    X   X",
		"X   X    X       XX+++++++xx       X    X   X",
		"X   X    X       XX+++++++xx       X    X   X",
		"X   X    X       XX+++++++xx       X    X   X",
		"X   X    X       XX+++++++xx       X    X   X",
		"X   X    X       XX+++++++xx       X    X   X",
		"X   X    X       XX#######XX       X    X   X",
		"X   X    X       XX+++++++XX       X    X   X",
		"X   X    X       XX+++++++XX       X    X   X",
		"X   X    X       XX+++++++XX       X    X   X",
		"X   x    x       xx+++++++XX       x    x    ",
		"X   x    x       xx+++++++XX       x    x    ",
		"X $ x    x       xx+++++++XXX      x    x    ",
		"X   x    x       xx+++++++XXXX     x    x    ",
		"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"],
		nExit: null,
		neExit: "Reflecting Pool",
		seExit: "Underhalls",
		sExit: null,
		swExit: null,
		nwExit: null,
		item: {enabled: true,
			skill: "wallJump",
			desc: "You can now wall jump! When you hit a wall, you'll grab it and slide down slowly. Jump while sliding to launch yourself away from the wall!"}}

maps["Garden Courtyard"] = {map:
	   ["XXXXXXXXXXXXXX******XXXXXX******XXXXXXXXXXXXX",
		"          ## X******X    X******X           X",
		"          ## X******X    X******X           X",
		"          ## X******X    X******X           X",
		"          ##  ||||||      ||||||            X",
		"X         ##  ||||||      ||||||  $         X",
		"X         ##  ||||||      ||||||            X",
		"XXX      XXXXX******XXXXXX******XXXXX       X",
		"X        X**************************X       X",
		"X        X**************************X       X",
		"X        X**************************X       X",
		"X        X**************************X       X",
		"X        X**************************X       X",
		"X        X**************************X       X",
		"X        X**************************X       X",
		"X        X**************************X       X",
		"X        X**************************X       X",
		"         XXXXX******XXXXXX******XXXXX       X",
		"          ++  ||||||      ||||||            X",
		"          ++  ||||||      ||||||            X",
		"          ++  ||||||      ||||||            X",
		"XXXXXXXXXXXXXX******XXXXXX******XXXXXXXXXXXXX"],
		nExit: null,
		neExit: null,
		seExit: null,
		sExit: null,
		swExit: "Old Shrine",
		nwExit: "Bell Tower",
		item: {enabled: true,
			skill: "dashSmash",
			desc: "You can now dash smash! You will smash through vertical green blocks while dashing!"}}

maps["Windswept Well"] = {map:
	   ["XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
		"                                            X",
		"                                            X",
		"                                            X",
		"                                            X",
		"XX                                          X",
		"X                                            ",
		"X                      X                     ",
		"X                      x                     ",
		"X                    XXXXX                   ",
		"X                  XXXx xXXX             XXXX",
		"X                XXX  x x  XXX              X",
		"X                 #   x x   #                ",
		"X                 #   x x   #                ",
		"X                 #   x$x   #                ",
		"X                 #   x x   #                ",
		"X                 #   XXX   #            XXXX",
		"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~X",
		"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~X",
		"~~~~~~~~~~~~~~~~~XXX~~~~~~~XXX~~~~~~~~~~~~~~X",
		"~~~~~~~~~~~~~~~~~XXX~~~~~~~XXX~~~~~~~~~~~~~~X",
		"XXXXXXXXXXXXXXXXXXXXXX~~~XXXXXXXXXXXXXXXXXXXX"],
		nExit: null,
		neExit: "Horizon Canopy",
		seExit: "Bell Tower",
		sExit: "Temple Center",
		swExit: "Reflecting Pool",
		nwExit: "Cloud Castle",
		item: {enabled: true,
			skill: "waterBreathing",
			desc: "You can now breathe underwater! You can act freely even in water over your head without drowning!"}}

maps["Caldera Lake"] = {map:
	   ["XXXXXXXXXXXXXXXXXXXXX``XXXXXXXXXXXXXXXXXXXXXX",
		"X                    ``                     X",
		"X                    ``                      ",
		"X                    ``                      ",
		"X                    ``                      ",
		"X                    ``                      ",
		"~~~~~~~~~`           ``                   XXX",
		"~~~~~~~~~~`          ``         |************",
		"~~~~~~~~~~~`         ``        |*************",
		"~~~~~~~~~~~~`        ``   X   |**************",
		"X~~~~~~~~~~~~`       ``      |***************",
		"X~~~~~~~~~~~~~`      ``      |XXXXXXXXXXXX***",
		"X~~~~~~~~~~~~~~`     ``      |            |||",
		"X~~~~~~~~~~~~~~~`    ``      |            |||",
		"X~~~~~~~~~~~~~~~~`   ``      |            |||",
		"X~~~~~~~~~~~~~~~~~`  `` X    |            |||",
		"X~~~~~~~~~~~~~~~~~~~X~~~X********************",
		"X~~~~~~~~~~~~~~~~~~~~~~~X********************",
		"X~~~~~~~~~~~~~~~~~~~~~~~X********************",
		"X~~~~~~~~~~~~~~~~~~~~~$~X********************",
		"X~~~~~~~~~~~~~~~~~~~~~~~X********************",
		"XXXXXXXXXXXXXXXXXXXXXXXXX********************"],
		nExit: "Temple Center",
		neExit: "Old Shrine",
		seExit: "Burning Abyss",
		sExit: null,
		swExit: null,
		nwExit: "Underhalls",
		item: {enabled: true,
			skill: "airDash",
			desc: "You can now air dash! Press Z in mid-air to dash at high speed! You can only air dash once before landing."}}

maps["Cloud Castle"] = {map:
	   ["XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
		"X                                           X",
		"X                                           X",
		"X                       $                   X",
		"X                                           X",
		"X                      XXX                  X",
		"X                      xxx                  X",
		"X                      xxx                  X",
		"X                      xxx                  X",
		"X                      xxx                  X",
		"X        X             xxx                  X",
		"X        x             xxx                  X",
		"X        x             xxx                   ",
		"X        x             xxX                   ",
		"X        x             xxx                   ",
		"X        x             xxx                   ",
		"X        x             xxx               XXXX",
		"X        x             xxx                  X",
		"X        x             xxx                  X",
		"X        x             xxx                  X",
		"X        x             xxx                  X",
		"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   X"],
		nExit: null,
		neExit: null,
		seExit: "Windswept Well",
		sExit: "Reflecting Pool",
		swExit: null,
		nwExit: null,
		item: {enabled: true,
			skill: "lavaSurf",
			desc: "You can now surf on lava! You won't take damage from stepping on lava while moving at full speed! If you stop, slow down, or turn around, you'll still take damage."}}

maps["Burning Abyss"] = {map:
	   ["*********************************************",
		"|||||||||||||||||||||||||||||||||||||||XXXXXX",
		"|||||||||||||||||||||||||||||||||||||||     X",
		"|||||||||||||||||||||||||||||||||||||||     X",
		"|||||||||||||||||||||||||||||||||||||||     X",
		"***************************************X    X",
		"***************************************X####X",
		"***************************************X    X",
		"***************************************X####X",
		"***************************************X    X",
		"***************************************X####X",
		"X*X*XXXXXXX*XX*XXXXXX*XXXX*XXXXX*XXX*XXX    X",
		"X| |       |  |      |    |     |   |       X",
		"X| |       |  |      |    |     |   |       X",
		"X|$|       |  |      |    |     |   |       X",
		"X| |       |  |      |    |     |   |       X",
		"XXXX       |  |      |    |     |   |       X",
		"X          |  |      |    |     |   |       X",
		"X          |  |      |    |     |   |       X",
		"****************************************XXXXX",
		"*********************************************",
		"*********************************************"],
		nExit: null,
		neExit: null,
		seExit: null,
		sExit: null,
		swExit: null,
		nwExit: "Caldera Lake",
		item: {enabled: true,
			skill: "jumpSmash",
			desc: "You can now jump smash! Your double jump will smash through green blocks overhead!"}}

maps["Horizon Canopy"] = {map:
	   ["XXXX*******************************XXXXXXXXXX",
		"X   |||||||||||||||||||||||||||||||         X",
		"X   |||||||||||||||||||||||||||||||         X",
		"X $ |||||||||||||||||||||||||||||||         X",
		"X   |||||||||||||||||||||||||||||||         X",
		"XXXX*******************************X########X",
		"X**********************************X########X",
		"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX########X",
		"X#######X########++++++++++########X########X",
		"X#######X########++++++++++########X########X",
		"X#######X########++++++++++########X########X",
		"X################++++++++++#################X",
		"X################++++++++++#################X",
		"X################++++++++++#################X",
		"X################++++++++++#################X",
		"X################X        X#################X",
		"X                X        X                 X",
		"                 X        X                 X",
		"                 X        X                 X",
		"                 X        X                 X",
		"                 X        X                 X",
		"XXXXXXXXXXXXXXXXXX        XXXXXXXXXXXXXXXXXXX",],
		nExit: null,
		neExit: null,
		seExit: null,
		sExit: "Bell Tower",
		swExit: "Windswept Well",
		nwExit: null,
		item: {enabled: true,
			skill: null,
			desc: "You win!!! It's over!!!"}}