worlds = ["", "Ethereal ", "Astral ", "Abyssal "];

regions = [{name:"Plains",
				color:"#cfc",
				material:"Flint ",
				materials:["Flint","Greenwood Log","Jute Scrap","Wolf Pelt","Lithic Core","Four-Leaf Clover","Warg Fang","Verdigris"],
				quests:[
					{name:"Drive monsters off the old road"},
					{name:"Clear the blockage damming the river"},
					{name:"Restore the run-down lumber mill"},
					{name:"Defend the old man's farm"},
					{name:"Defeat the bandit queen"}],
				prefixes:[[],
					["Giant ","Dire ","Death "],
					["Blood ","Wolf ","Blight "],
					["Giant ","Crawling ","Blight "],
					["Hobgoblin ","Goblin ","Zombie "]],
				suffixes:[[],
					["Lion","Wolf","Hyena"],
					["Jackal","Hawk","Spider"],
					["Rat","Claw","Weasel"],
					["Soldier","Scout","Necromancer"]]},
		   {name:"Forest",
				color:"#8f8",
				material:"Darkwood ",
				materials:["Iron Ore","Oak Log","Linen Scrap","Bear Pelt","Lump of Coal","Spirit Mushroom","Venom Sac","Chromium Filigree"],
				quests:[
					{name:"Harvest horned melons from the orchard"},
					{name:"Plant trees in the deforested area"},
					{name:"Survive an ambush in the natural bower"},
					{name:"Clear the vines choking the great tree"},
					{name:"Defeat the myconid sovereign"}],
				prefixes:[[],
					["Awakened ","Assassin ","Owl "],
					["Giant ","Ice ","Phase "],
					["Violet ","Thorn ","Musk "],
					["Vine ","Needle ","Twig "]],
				suffixes:[[],
					["Tree","Bear","Tiger"],
					["Spider","Vine","Spore"],
					["Fungus","Slinger","Creeper"],
					["Blight","Dog","Horror"]]},
		   {name:"Lake",
				color:"#ccf",
				material:"Copper ",
				materials:["Silver Ore","Palm Log","Cotton Scrap","Lion Pelt","Gold Ore","Crystal Iris","Sahuagin Scales","Rhodium Sliver"],
				quests:[
					{name:"Defend your camp in the middle of the night"},
					{name:"Drive monsters out of the rainbow glen"},
					{name:"Climb the treacherous waterfall"},
					{name:"Row to the middle of the crystal lake"},
					{name:"Defeat the merrow barbarian"}],
				prefixes:[[],
					["Storm ","Horizon ","Deep "],
					["Tortle ","Harpy ","Sahuagin "],
					["Tortle ","Harpy ","Sahuagin "],
					["Giant ","Poisonous ","Cursed "]],
				suffixes:[[],
					["Scion","Manticore","Priest"],
					["Berserker","Commander","Priestess"],
					["Warrior","Skirmisher","Druid"],
					["Crab","Toad","Lizard"]]},
		   {name:"Steppes",
				color:"#ffc",
				material:"Lodestone ",
				materials:["Mithril Ore","Acacia Log","Satin Scrap","Tiger Pelt","Lunar Rock","Thunder Daisy","Ancient Bone","Stardust"],
				quests:[
					{name:"Drive monsters out of the old stone quarry"},
					{name:"Drain the necrotic oil pond"},
					{name:"Restore the old weather post"},
					{name:"Defend the abandoned factory"},
					{name:"Defeat the rogue golem"}],
				prefixes:[[],
					["Armored ","Saber-Tooth ","Crag "],
					["Troll ","Ogre ","Ettin "],
					["Axe ","Crag ","Clockwork "],
					["Metal ","Giant ","Sand "]],
				suffixes:[[],
					["Ogre","Tiger","Basilisk"],
					["Zombie","Skeleton","Ghost"],
					["Moa","Cat","Dragon"],
					["Lizard","Rat","Wasp"]]},
		   {name:"Lava Flow",
				color:"#fcc",
				material:"Bronze ",
				materials:["Orichalcum Ore","Banyan Log","Damask Scrap","Manticore Pelt","Fire Opal","Fire Orchid","Phoenix Ash","Seed of Life"],
				quests:[
					{name:"Dig out the buried tower"},
					{name:"Explore the volcano's fingers"},
					{name:"Investigate the unusual lava flow"},
					{name:"Uncover the location of the lost city"},
					{name:"Defeat the huge magma elemental"}],
				prefixes:[[],
					["Hell ","Twisted ","Emberhorn "],
					["Gnoll ","Hyena ","Magmin "],
					["Gnoll ","Hyena ","Magmin "],
					["Giant ","Magma ","Fire "]],
				suffixes:[[],
					["Minotaur","Stag","Hound"],
					["Darkfang","Packleader","Igniter"],
					["Gnawer","Hunter","Witherer"],
					["Beetle","Snake","Mephit"]]},
		   {name:"Mountain",
				color:"#ff8",
				material:"Brass ",
				materials:[],
				quests:[
					{name:"Pick herbs for the apothecary"},
					{name:"Clear the gate to the old road"},
					{name:"Defend the old man's farm"},
					{name:"Restore the old lumber mill"},
					{name:"Defeat the bandit queen"}],
				prefixes:[[],
					["Demon ","Dragon ","Phoenix "],
					["Troll ","Ogre ","Ettin "],
					["Ghost ","Zombie ","Skeleton "],
					["Orc ","Goblin ","Kobold "]],
				suffixes:[[],
					["Lord","Slayer","Guardian"],
					["Mage","Berserker","Brute"],
					["Avenger","Runner","Minion"],
					["Shaman","Scout","Soldier"]]},
		   {name:"Swamp",
				color:"#fcf",
				material:"Iron ",
				materials:[],
				quests:[
					{name:"Pick herbs for the apothecary"},
					{name:"Clear the gate to the old road"},
					{name:"Defend the old man's farm"},
					{name:"Restore the old lumber mill"},
					{name:"Defeat the bandit queen"}],
				prefixes:[[],
					["Demon ","Dragon ","Phoenix "],
					["Troll ","Ogre ","Ettin "],
					["Ghost ","Zombie ","Skeleton "],
					["Orc ","Goblin ","Kobold "]],
				suffixes:[[],
					["Lord","Slayer","Guardian"],
					["Mage","Berserker","Brute"],
					["Avenger","Runner","Minion"],
					["Shaman","Scout","Soldier"]]},
		   {name:"Jungle",
				color:"#8c8",
				material:"Steel ",
				materials:[],
				quests:[
					{name:"Pick herbs for the apothecary"},
					{name:"Clear the gate to the old road"},
					{name:"Defend the old man's farm"},
					{name:"Restore the old lumber mill"},
					{name:"Defeat the bandit queen"}],
				prefixes:[[],
					["Demon ","Dragon ","Phoenix "],
					["Troll ","Ogre ","Ettin "],
					["Ghost ","Zombie ","Skeleton "],
					["Orc ","Goblin ","Kobold "]],
				suffixes:[[],
					["Lord","Slayer","Guardian"],
					["Mage","Berserker","Brute"],
					["Avenger","Runner","Minion"],
					["Shaman","Scout","Soldier"]]},
		   {name:"Cliffside",
				color:"#cc8",
				material:"Coldsteel ",
				materials:[],
				quests:[
					{name:"Pick herbs for the apothecary"},
					{name:"Clear the gate to the old road"},
					{name:"Defend the old man's farm"},
					{name:"Restore the old lumber mill"},
					{name:"Defeat the bandit queen"}],
				prefixes:[[],
					["Demon ","Dragon ","Phoenix "],
					["Troll ","Ogre ","Ettin "],
					["Ghost ","Zombie ","Skeleton "],
					["Orc ","Goblin ","Kobold "]],
				suffixes:[[],
					["Lord","Slayer","Guardian"],
					["Mage","Berserker","Brute"],
					["Avenger","Runner","Minion"],
					["Shaman","Scout","Soldier"]]},
		   {name:"Shattered Island",
				color:"#8cf",
				material:"Chromium ",
				materials:[],
				quests:[
					{name:"Pick herbs for the apothecary"},
					{name:"Clear the gate to the old road"},
					{name:"Defend the old man's farm"},
					{name:"Restore the old lumber mill"},
					{name:"Defeat the bandit queen"}],
				prefixes:[[],
					["Demon ","Dragon ","Phoenix "],
					["Troll ","Ogre ","Ettin "],
					["Ghost ","Zombie ","Skeleton "],
					["Orc ","Goblin ","Kobold "]],
				suffixes:[[],
					["Lord","Slayer","Guardian"],
					["Mage","Berserker","Brute"],
					["Avenger","Runner","Minion"],
					["Shaman","Scout","Soldier"]]},
		   {name:"Mud Flats",
				color:"#cff",
				material:"Silver ",
				materials:[],
				quests:[
					{name:"Pick herbs for the apothecary"},
					{name:"Clear the gate to the old road"},
					{name:"Defend the old man's farm"},
					{name:"Restore the old lumber mill"},
					{name:"Defeat the bandit queen"}],
				prefixes:[[],
					["Demon ","Dragon ","Phoenix "],
					["Troll ","Ogre ","Ettin "],
					["Ghost ","Zombie ","Skeleton "],
					["Orc ","Goblin ","Kobold "]],
				suffixes:[[],
					["Lord","Slayer","Guardian"],
					["Mage","Berserker","Brute"],
					["Avenger","Runner","Minion"],
					["Shaman","Scout","Soldier"]]},
		   {name:"Riverlands",
				color:"#88f",
				material:"Gold ",
				materials:[],
				quests:[
					{name:"Pick herbs for the apothecary"},
					{name:"Clear the gate to the old road"},
					{name:"Defend the old man's farm"},
					{name:"Restore the old lumber mill"},
					{name:"Defeat the bandit queen"}],
				prefixes:[[],
					["Demon ","Dragon ","Phoenix "],
					["Troll ","Ogre ","Ettin "],
					["Ghost ","Zombie ","Skeleton "],
					["Orc ","Goblin ","Kobold "]],
				suffixes:[[],
					["Lord","Slayer","Guardian"],
					["Mage","Berserker","Brute"],
					["Avenger","Runner","Minion"],
					["Shaman","Scout","Soldier"]]},
		   {name:"Reef",
				color:"#88c",
				material:"Electrum ",
				materials:[],
				quests:[
					{name:"Pick herbs for the apothecary"},
					{name:"Clear the gate to the old road"},
					{name:"Defend the old man's farm"},
					{name:"Restore the old lumber mill"},
					{name:"Defeat the bandit queen"}],
				prefixes:[[],
					["Demon ","Dragon ","Phoenix "],
					["Troll ","Ogre ","Ettin "],
					["Ghost ","Zombie ","Skeleton "],
					["Orc ","Goblin ","Kobold "]],
				suffixes:[[],
					["Lord","Slayer","Guardian"],
					["Mage","Berserker","Brute"],
					["Avenger","Runner","Minion"],
					["Shaman","Scout","Soldier"]]},
		   {name:"Snow Drifts",
				color:"#8ff",
				material:"Platinum ",
				materials:[],
				quests:[
					{name:"Pick herbs for the apothecary"},
					{name:"Clear the gate to the old road"},
					{name:"Defend the old man's farm"},
					{name:"Restore the old lumber mill"},
					{name:"Defeat the bandit queen"}],
				prefixes:[[],
					["Demon ","Dragon ","Phoenix "],
					["Troll ","Ogre ","Ettin "],
					["Ghost ","Zombie ","Skeleton "],
					["Orc ","Goblin ","Kobold "]],
				suffixes:[[],
					["Lord","Slayer","Guardian"],
					["Mage","Berserker","Brute"],
					["Avenger","Runner","Minion"],
					["Shaman","Scout","Soldier"]]},
		   {name:"Glacier",
				color:"#8cc",
				material:"Crystalline ",
				materials:[],
				quests:[
					{name:"Pick herbs for the apothecary"},
					{name:"Clear the gate to the old road"},
					{name:"Defend the old man's farm"},
					{name:"Restore the old lumber mill"},
					{name:"Defeat the bandit queen"}],
				prefixes:[[],
					["Demon ","Dragon ","Phoenix "],
					["Troll ","Ogre ","Ettin "],
					["Ghost ","Zombie ","Skeleton "],
					["Orc ","Goblin ","Kobold "]],
				suffixes:[[],
					["Lord","Slayer","Guardian"],
					["Mage","Berserker","Brute"],
					["Avenger","Runner","Minion"],
					["Shaman","Scout","Soldier"]]},
		   {name:"Plateau",
				color:"#f8f",
				material:"Marble ",
				materials:[],
				quests:[
					{name:"Pick herbs for the apothecary"},
					{name:"Clear the gate to the old road"},
					{name:"Defend the old man's farm"},
					{name:"Restore the old lumber mill"},
					{name:"Defeat the bandit queen"}],
				prefixes:[[],
					["Demon ","Dragon ","Phoenix "],
					["Troll ","Ogre ","Ettin "],
					["Ghost ","Zombie ","Skeleton "],
					["Orc ","Goblin ","Kobold "]],
				suffixes:[[],
					["Lord","Slayer","Guardian"],
					["Mage","Berserker","Brute"],
					["Avenger","Runner","Minion"],
					["Shaman","Scout","Soldier"]]},
		   {name:"Canyon",
				color:"#8fc",
				material:"Titanium ",
				materials:[],
				quests:[
					{name:"Pick herbs for the apothecary"},
					{name:"Clear the gate to the old road"},
					{name:"Defend the old man's farm"},
					{name:"Restore the old lumber mill"},
					{name:"Defeat the bandit queen"}],
				prefixes:[[],
					["Demon ","Dragon ","Phoenix "],
					["Troll ","Ogre ","Ettin "],
					["Ghost ","Zombie ","Skeleton "],
					["Orc ","Goblin ","Kobold "]],
				suffixes:[[],
					["Lord","Slayer","Guardian"],
					["Mage","Berserker","Brute"],
					["Avenger","Runner","Minion"],
					["Shaman","Scout","Soldier"]]},
		   {name:"Valley",
				color:"#cf8",
				material:"Mithril ",
				materials:[],
				quests:[
					{name:"Pick herbs for the apothecary"},
					{name:"Clear the gate to the old road"},
					{name:"Defend the old man's farm"},
					{name:"Restore the old lumber mill"},
					{name:"Defeat the bandit queen"}],
				prefixes:[[],
					["Demon ","Dragon ","Phoenix "],
					["Troll ","Ogre ","Ettin "],
					["Ghost ","Zombie ","Skeleton "],
					["Orc ","Goblin ","Kobold "]],
				suffixes:[[],
					["Lord","Slayer","Guardian"],
					["Mage","Berserker","Brute"],
					["Avenger","Runner","Minion"],
					["Shaman","Scout","Soldier"]]},
		   {name:"Boneyard",
				color:"#c8f",
				material:"Ethereal ",
				materials:[],
				quests:[
					{name:"Pick herbs for the apothecary"},
					{name:"Clear the gate to the old road"},
					{name:"Defend the old man's farm"},
					{name:"Restore the old lumber mill"},
					{name:"Defeat the bandit queen"}],
				prefixes:[[],
					["Demon ","Dragon ","Phoenix "],
					["Troll ","Ogre ","Ettin "],
					["Ghost ","Zombie ","Skeleton "],
					["Orc ","Goblin ","Kobold "]],
				suffixes:[[],
					["Lord","Slayer","Guardian"],
					["Mage","Berserker","Brute"],
					["Avenger","Runner","Minion"],
					["Shaman","Scout","Soldier"]]},
		   {name:"Storm's Eye",
				color:"#c8c",
				material:"Stormforged ",
				materials:[],
				quests:[
					{name:"Pick herbs for the apothecary"},
					{name:"Clear the gate to the old road"},
					{name:"Defend the old man's farm"},
					{name:"Restore the old lumber mill"},
					{name:"Defeat the bandit queen"}],
				prefixes:[[],
					["Demon ","Dragon ","Phoenix "],
					["Troll ","Ogre ","Ettin "],
					["Ghost ","Zombie ","Skeleton "],
					["Orc ","Goblin ","Kobold "]],
				suffixes:[[],
					["Lord","Slayer","Guardian"],
					["Mage","Berserker","Brute"],
					["Avenger","Runner","Minion"],
					["Shaman","Scout","Soldier"]]},
		   {name:"Hunting Grounds",
				color:"#f8c",
				material:"Adamantium ",
				materials:[],
				quests:[
					{name:"Pick herbs for the apothecary"},
					{name:"Clear the gate to the old road"},
					{name:"Defend the old man's farm"},
					{name:"Restore the old lumber mill"},
					{name:"Defeat the bandit queen"}],
				prefixes:[[],
					["Demon ","Dragon ","Phoenix "],
					["Troll ","Ogre ","Ettin "],
					["Ghost ","Zombie ","Skeleton "],
					["Orc ","Goblin ","Kobold "]],
				suffixes:[[],
					["Lord","Slayer","Guardian"],
					["Mage","Berserker","Brute"],
					["Avenger","Runner","Minion"],
					["Shaman","Scout","Soldier"]]},
		   {name:"Desert",
				color:"#fc8",
				material:"Orichalcum ",
				materials:[],
				quests:[
					{name:"Pick herbs for the apothecary"},
					{name:"Clear the gate to the old road"},
					{name:"Defend the old man's farm"},
					{name:"Restore the old lumber mill"},
					{name:"Defeat the bandit queen"}],
				prefixes:[[],
					["Demon ","Dragon ","Phoenix "],
					["Troll ","Ogre ","Ettin "],
					["Ghost ","Zombie ","Skeleton "],
					["Orc ","Goblin ","Kobold "]],
				suffixes:[[],
					["Lord","Slayer","Guardian"],
					["Mage","Berserker","Brute"],
					["Avenger","Runner","Minion"],
					["Shaman","Scout","Soldier"]]},
		   {name:"Volcano",
				color:"#f88",
				material:"Obsidian ",
				materials:[],
				quests:[
					{name:"Pick herbs for the apothecary"},
					{name:"Clear the gate to the old road"},
					{name:"Defend the old man's farm"},
					{name:"Restore the old lumber mill"},
					{name:"Defeat the bandit queen"}],
				prefixes:[[],
					["Demon ","Dragon ","Phoenix "],
					["Troll ","Ogre ","Ettin "],
					["Ghost ","Zombie ","Skeleton "],
					["Orc ","Goblin ","Kobold "]],
				suffixes:[[],
					["Lord","Slayer","Guardian"],
					["Mage","Berserker","Brute"],
					["Avenger","Runner","Minion"],
					["Shaman","Scout","Soldier"]]},
		   {name:"Crater",
				color:"#c88",
				material:"Starmetal ",
				materials:[],
				quests:[
					{name:"Pick herbs for the apothecary"},
					{name:"Clear the gate to the old road"},
					{name:"Defend the old man's farm"},
					{name:"Restore the old lumber mill"},
					{name:"Defeat the bandit queen"}],
				prefixes:[[],
					["Demon ","Dragon ","Phoenix "],
					["Troll ","Ogre ","Ettin "],
					["Ghost ","Zombie ","Skeleton "],
					["Orc ","Goblin ","Kobold "]],
				suffixes:[[],
					["Lord","Slayer","Guardian"],
					["Mage","Berserker","Brute"],
					["Avenger","Runner","Minion"],
					["Shaman","Scout","Soldier"]]},
		   {name:"Ash Wastes",
				color:"#888",
				material:"Diamond ",
				materials:[],
				quests:[
					{name:"Pick herbs for the apothecary"},
					{name:"Clear the gate to the old road"},
					{name:"Defend the old man's farm"},
					{name:"Restore the old lumber mill"},
					{name:"Defeat the bandit queen"}],
				prefixes:[[],
					["Demon ","Dragon ","Phoenix "],
					["Troll ","Ogre ","Ettin "],
					["Ghost ","Zombie ","Skeleton "],
					["Orc ","Goblin ","Kobold "]],
				suffixes:[[],
					["Lord","Slayer","Guardian"],
					["Mage","Berserker","Brute"],
					["Avenger","Runner","Minion"],
					["Shaman","Scout","Soldier"]]}];